export const GET_WATCH_STOCK_LIST = "app/GET_WATCH_STOCK_LIST";
export const GET_WATCH_STOCK = "app/GET_WATCH_STOCK";
export const POST_WATCH_STOCK = "app/POST_WATCH_STOCK";
export const DELETE_WATCH_STOCK = "app/DELETE_WATCH_STOCK";
